"""harden internal ledger integrity

Revision ID: 030557b0ceb7
Revises: 9a3badf77776
Create Date: 2026-10-05 03:19:03.436228

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '030557b0ceb7'
down_revision: Union[str, Sequence[str], None] = '9a3badf77776'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        'ix_internal_ledger_application_date',
        'internal_ledger',
        ['application_id', 'transaction_date'],
        unique=False
    )

    op.create_index(
        'ix_internal_ledger_disbursement_date',
        'internal_ledger',
        ['disbursement_id', 'transaction_date'],
        unique=False
    )

    op.create_unique_constraint(
        'uq_internal_ledger_disbursement_transaction_type',
        'internal_ledger',
        ['disbursement_id', 'transaction_type']
    )
    # ### end Alembic commands ###
    
    op.create_check_constraint(
        'ck_internal_ledger_transaction_amount_non_negative',
        'internal_ledger',
        'transaction_amount >= 0',
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        'ck_internal_ledger_transaction_amount_non_negative',
        'internal_ledger',
        type_='check',
    )
    
    op.drop_constraint(
        'uq_internal_ledger_disbursement_transaction_type',
        'internal_ledger',
        type_='unique')
    
    op.drop_index(
        'ix_internal_ledger_disbursement_date',
        table_name='internal_ledger'
    )
    
    op.drop_index(
        'ix_internal_ledger_application_date', 
        table_name='internal_ledger'
    )
    # ### end Alembic commands ###
