"""add policy governance fields

Revision ID: 061e2797c27e
Revises: 2d34f96faa99
Create Date: 2026-10-03 06:37:58.276761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '061e2797c27e'
down_revision: Union[str, Sequence[str], None] = '2d34f96faa99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_logs',
    sa.Column('previous_state', 
    sa.Text(), 
    nullable=True))

    op.add_column('audit_logs', 
    sa.Column('new_state', 
    sa.Text(), 
    nullable=True))

    op.add_column('audit_logs', 
    sa.Column('request_reference', 
    sa.String(length=150), 
    nullable=True))
    
    op.add_column(
    'credit_decisions',
    sa.Column('effective_from',
    sa.String(length=20), 
    nullable=True))
    
    op.add_column(
    'credit_decisions',
    sa.Column('effective_to', 
    sa.String(length=20), 
    nullable=True))
    
    op.execute(
    "UPDATE credit_decisions "
    "SET effective_from = '2026-09-01' "
    "WHERE effective_from IS NULL"
    )

    op.alter_column(
    'credit_decisions',
    'effective_from',
    existing_type=sa.String(length=20),
    nullable=False,
    )
    
    op.create_foreign_key(
    'fk_reconciliation_application_id', 
    'reconciliation', 
    'loan_applications', 
    ['application_id'], 
    ['application_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(
    'fk_reconciliation_application_id', 
    'reconciliation', 
    type_='foreignkey')

    op.drop_column('credit_decisions', 'effective_to')
    op.drop_column('credit_decisions', 'effective_from')
    op.drop_column('audit_logs', 'request_reference')
    op.drop_column('audit_logs', 'new_state')
    op.drop_column('audit_logs', 'previous_state')
    # ### end Alembic commands ###
