"""harden agreement integrity

Revision ID: 0e7978a76f92
Revises: 4960a6c55d19
Create Date: 2026-10-05 06:39:20.814467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e7978a76f92'
down_revision: Union[str, Sequence[str], None] = '4960a6c55d19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        'ix_agreements_application_created', 
        'agreements', 
        ['application_id', 'created_at'], 
        unique=False
    )

    op.create_unique_constraint(
        'uq_agreements_sanction',
        'agreements',
        ['sanction_id']
    )

    op.create_check_constraint(
        'ck_agreements_status',
        'agreements',
        "agreement_status IN ('CREATED', 'ACTIVE', 'COMPLETED', 'CANCELLED')",
    )

    op.create_check_constraint(
        'ck_agreements_esign_status',
        'agreements',
        "esign_status IN ('NOT_STARTED', 'INITIATED', 'SIGNED', 'FAILED')",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_constraint(
        'ck_agreements_esign_status',
        'agreements',
        type_='check',
    )

    op.drop_constraint(
        'ck_agreements_status',
        'agreements',
        type_='check',
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        'uq_agreements_sanction',
        'agreements',
        type_='unique'
    )

    op.drop_index(
        'ix_agreements_application_created',
        table_name='agreements'
    )
    # ### end Alembic commands ###
