"""harden audit log integrity

Revision ID: 1aaee24ede4e
Revises: 37963316134f
Create Date: 2026-10-05 07:30:44.638349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1aaee24ede4e'
down_revision: Union[str, Sequence[str], None] = '37963316134f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_audit_logs_application_created', 'audit_logs', ['application_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_audit_logs_application_created', table_name='audit_logs')
    # ### end Alembic commands ###
