"""harden credit decision integrity

Revision ID: 317147dd64fa
Revises: aa996b5f23c2
Create Date: 2026-10-05 01:17:12.737641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '317147dd64fa'
down_revision: Union[str, Sequence[str], None] = 'aa996b5f23c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('credit_decisions', 'policy_version',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.create_index('ix_credit_decisions_application_created', 'credit_decisions', ['application_id', 'created_at'], unique=False)
    # ### end Alembic commands ###
    op.create_check_constraint(
        "ck_credit_decisions_decision",
        "credit_decisions",
        "decision IN ('APPROVE', 'REFER', 'REJECT')",
    )

    op.create_check_constraint(
        "ck_credit_decisions_risk_grade",
        "credit_decisions",
        "risk_grade IS NULL OR risk_grade IN ('A', 'B', 'C', 'D', 'E')",
    )

    op.create_check_constraint(
        "ck_credit_decisions_pd_range",
        "credit_decisions",
        "probability_of_default IS NULL OR "
        "(probability_of_default >= 0 AND probability_of_default <= 1)",
    )

    op.create_check_constraint(
        "ck_credit_decisions_confidence_range",
        "credit_decisions",
        "confidence IS NULL OR "
        "(confidence >= 0 AND confidence <= 1)",
    )
    op.create_check_constraint(
        "ck_credit_decisions_foir_non_negative",
        "credit_decisions",
        "foir IS NULL OR foir >= 0",
    )

    op.create_check_constraint(
        "ck_credit_decisions_foir_max_100",
        "credit_decisions",
        "foir IS NULL OR foir <= 100",
    )

    op.create_check_constraint(
        "ck_credit_decisions_recommended_amount_non_negative",
        "credit_decisions",
        "recommended_amount IS NULL OR recommended_amount >= 0",
    )

    op.create_check_constraint(
        "ck_credit_decisions_recommended_emi_non_negative",
        "credit_decisions",
        "recommended_emi IS NULL OR recommended_emi >= 0",
    )

    op.create_check_constraint(
        "ck_credit_decisions_recommended_tenure_non_negative",
        "credit_decisions",
        "recommended_tenure IS NULL OR recommended_tenure >= 0",
    )

    op.create_check_constraint(
        "ck_credit_decisions_credit_score_non_negative",
        "credit_decisions",
        "credit_score IS NULL OR credit_score >= 0",
    )

    op.create_check_constraint(
        "ck_credit_decisions_affordability_score_range",
        "credit_decisions",
        "affordability_score IS NULL OR "
        "(affordability_score >= 0 AND affordability_score <= 100)",
    )

    op.create_check_constraint(
        "ck_credit_decisions_repayment_propensity_range",
        "credit_decisions",
        "repayment_propensity IS NULL OR "
        "(repayment_propensity >= 0 AND repayment_propensity <= 100)",
    )

    op.create_check_constraint(
        "ck_credit_decisions_fraud_score_range",
        "credit_decisions",
        "fraud_score IS NULL OR "
        "(fraud_score >= 0 AND fraud_score <= 100)",
    )

    op.create_check_constraint(
        "ck_credit_decisions_income_stability_score_range",
        "credit_decisions",
        "income_stability_score IS NULL OR "
        "(income_stability_score >= 0 AND income_stability_score <= 100)",
    )

    op.create_check_constraint(
        "ck_credit_decisions_risk_segment",
        "credit_decisions",
        "risk_segment IS NULL OR "
        "risk_segment IN ('LOW_RISK', 'MEDIUM_RISK', 'HIGH_RISK')",
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_constraint(
        "ck_credit_decisions_confidence_range",
        "credit_decisions",
        type_="check",
    )

    op.drop_constraint(
        "ck_credit_decisions_pd_range",
        "credit_decisions",
        type_="check",
    )

    op.drop_constraint(
        "ck_credit_decisions_risk_grade",
        "credit_decisions",
        type_="check",
    )

    op.drop_constraint(
        "ck_credit_decisions_decision",
        "credit_decisions",
        type_="check",
    )

    op.drop_constraint(
        "ck_credit_decisions_credit_score_non_negative",
        "credit_decisions",
        type_="check",
    )

    op.drop_constraint(
        "ck_credit_decisions_recommended_tenure_non_negative",
        "credit_decisions",
        type_="check",
    )

    op.drop_constraint(
        "ck_credit_decisions_recommended_emi_non_negative",
        "credit_decisions",
        type_="check",
    )

    op.drop_constraint(
        "ck_credit_decisions_recommended_amount_non_negative",
        "credit_decisions",
        type_="check",
    )

    op.drop_constraint(
        "ck_credit_decisions_foir_max_100",
        "credit_decisions",
        type_="check",
    )

    op.drop_constraint(
        "ck_credit_decisions_foir_non_negative",
        "credit_decisions",
        type_="check",
    )

    op.drop_constraint(
        "ck_credit_decisions_risk_segment",
        "credit_decisions",
        type_="check",
    )

    op.drop_constraint(
        "ck_credit_decisions_income_stability_score_range",
        "credit_decisions",
        type_="check",
    )

    op.drop_constraint(
        "ck_credit_decisions_fraud_score_range",
        "credit_decisions",
        type_="check",
    )

    op.drop_constraint(
        "ck_credit_decisions_repayment_propensity_range",
        "credit_decisions",
        type_="check",
    )

    op.drop_constraint(
        "ck_credit_decisions_affordability_score_range",
        "credit_decisions",
        type_="check",
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_credit_decisions_application_created', table_name='credit_decisions')
    op.alter_column('credit_decisions', 'policy_version',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    # ### end Alembic commands ###
