"""harden mandate integrity

Revision ID: 37963316134f
Revises: 0e7978a76f92
Create Date: 2026-10-05 06:53:27.882567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37963316134f'
down_revision: Union[str, Sequence[str], None] = '0e7978a76f92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        'ix_mandates_status_created',
        'mandates', 
        ['status', 'created_at'], 
        unique=False
    )

    op.create_unique_constraint(
        'uq_mandates_application',
        'mandates',
        ['application_id']
    )

    # ### end Alembic commands ###
    op.create_check_constraint(
        "ck_mandates_status",
        "mandates",
        "status IN ('INITIATED', 'COMPLETED', 'FAILED')",
)


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_constraint(
        'ck_mandates_status',
        'mandates',
        type_='check',
    )
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        'uq_mandates_application', 
        'mandates', 
        type_='unique'
    )

    op.drop_index(
        'ix_mandates_status_created', 
        table_name='mandates'
    )
    # ### end Alembic commands ###
