"""harden sanction integrity

Revision ID: 4960a6c55d19
Revises: dd8e95c8b927
Create Date: 2026-10-05 06:32:14.009380

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4960a6c55d19'
down_revision: Union[str, Sequence[str], None] = 'dd8e95c8b927'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        'uq_sanctions_application',
        'sanctions', 
        ['application_id']
    )

    # ### end Alembic commands ###
    op.create_check_constraint(
        "ck_sanctions_amount_positive",
        "sanctions",
        "sanctioned_amount > 0",
    )

    op.create_check_constraint(
        "ck_sanctions_tenure_positive",
        "sanctions",
        "sanctioned_tenure > 0",
    )

    op.create_check_constraint(
        "ck_sanctions_emi_non_negative",
        "sanctions",
        "sanctioned_emi IS NULL OR sanctioned_emi >= 0",
    )

    op.create_check_constraint(
        "ck_sanctions_interest_rate_non_negative",
        "sanctions",
        "interest_rate IS NULL OR interest_rate >= 0",
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_constraint(
        "ck_sanctions_interest_rate_non_negative",
        "sanctions",
        type_="check",
    )

    op.drop_constraint(
        "ck_sanctions_emi_non_negative",
        "sanctions",
        type_="check",
    )

    op.drop_constraint(
        "ck_sanctions_tenure_positive",
        "sanctions",
        type_="check",
    )

    op.drop_constraint(
        "ck_sanctions_amount_positive",
        "sanctions",
        type_="check",
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        'uq_sanctions_application',
        'sanctions',
        type_='unique'
    )
    # ### end Alembic commands ###
