"""harden collection integrity

Revision ID: 4bcdf290671c
Revises: 8b21df9aae73
Create Date: 2026-10-05 04:03:02.165179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4bcdf290671c'
down_revision: Union[str, Sequence[str], None] = '8b21df9aae73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        'ix_collections_application_created',
        'collections',
        ['application_id', 'created_at'],
        unique=False
    )

    op.create_index(
        'ix_collections_schedule_created',
        'collections',
        ['repayment_schedule_id', 'created_at'],
        unique=False
    )

    op.create_unique_constraint(
        'uq_collections_collection_reference',
        'collections',
        ['collection_reference']
    )

    op.create_check_constraint(
        'ck_collections_due_amount_non_negative',
        'collections',
        'due_amount >= 0',
    )

    op.create_check_constraint(
        'ck_collections_collected_amount_non_negative',
        'collections',
        'collected_amount >= 0',
    )

    op.create_check_constraint(
        'ck_collections_outstanding_amount_non_negative',
        'collections',
        'outstanding_amount >= 0',
    )

    op.create_check_constraint(
        'ck_collections_days_past_due_non_negative',
        'collections',
        'days_past_due >= 0',
    )

    op.create_check_constraint(
        'ck_collections_collected_amount_not_over_due',
        'collections',
        'collected_amount <= due_amount',
    )

    op.create_check_constraint(
        'ck_collections_outstanding_amount_not_over_due',
        'collections',
        'outstanding_amount <= due_amount',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_constraint(
        'ck_collections_outstanding_amount_not_over_due',
        'collections',
        type_='check',
    )

    op.drop_constraint(
        'ck_collections_collected_amount_not_over_due',
        'collections',
        type_='check',
    )

    op.drop_constraint(
        'ck_collections_days_past_due_non_negative',
        'collections',
        type_='check',
    )

    op.drop_constraint(
        'ck_collections_outstanding_amount_non_negative',
        'collections',
        type_='check',
    )

    op.drop_constraint(
        'ck_collections_collected_amount_non_negative',
        'collections',
        type_='check',
    )

    op.drop_constraint(
        'ck_collections_due_amount_non_negative',
        'collections',
        type_='check',
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        'uq_collections_collection_reference',
        'collections',
        type_='unique'
    )

    op.drop_index(
        'ix_collections_schedule_created',
        table_name='collections'
    )

    op.drop_index(
        'ix_collections_application_created',
        table_name='collections'
    )
    # ### end Alembic commands ###