"""harden model registry integrity

Revision ID: 506672d91f5c
Revises: d7df51ef3783
Create Date: 2026-10-05 08:30:54.262199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '506672d91f5c'
down_revision: Union[str, Sequence[str], None] = 'd7df51ef3783'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint(
        "ck_model_registry_roc_auc_range",
        "model_registry",
        "roc_auc IS NULL OR (roc_auc >= 0 AND roc_auc <= 1)",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "ck_model_registry_roc_auc_range",
        "model_registry",
        type_="check",
    )
    # ### end Alembic commands ###
