"""harden repayment schedule integrity

Revision ID: 527b7e142136
Revises: 4bcdf290671c
Create Date: 2026-10-05 04:53:35.325055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '527b7e142136'
down_revision: Union[str, Sequence[str], None] = '4bcdf290671c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        'ix_repayment_schedules_application_installment',
        'repayment_schedules',
        ['application_id', 'installment_number'],
        unique=False
    )

    op.create_index(
        'ix_repayment_schedules_disbursement_installment',
        'repayment_schedules',
        ['disbursement_id', 'installment_number'],
        unique=False
    )

    op.create_unique_constraint(
        'uq_repayment_schedules_disbursement_installment',
        'repayment_schedules',
        ['disbursement_id', 'installment_number']
    )
    # ### end Alembic commands ###
    op.create_check_constraint(
        'ck_repayment_schedules_installment_number_positive',
        'repayment_schedules',
        'installment_number >= 1',
    )

    op.create_check_constraint(
        'ck_repayment_schedules_principal_due_non_negative',
        'repayment_schedules',
        'principal_due >= 0',
    )

    op.create_check_constraint(
        'ck_repayment_schedules_interest_due_non_negative',
        'repayment_schedules',
        'interest_due >= 0',
    )

    op.create_check_constraint(
        'ck_repayment_schedules_total_due_non_negative',
        'repayment_schedules',
        'total_due >= 0',
    )

    op.create_check_constraint(
        'ck_repayment_schedules_outstanding_principal_non_negative',
        'repayment_schedules',
        'outstanding_principal >= 0',
    )

    op.create_check_constraint(
        'ck_repayment_schedules_total_due_consistency',
        'repayment_schedules',
        'total_due = principal_due + interest_due',
    )

    op.create_check_constraint(
        'ck_repayment_schedules_status',
        'repayment_schedules',
        "status IN ('PENDING', 'PAID')",
    )

    op.create_check_constraint(
        'ck_repayment_schedules_paid_at_required',
        'repayment_schedules',
        "status <> 'PAID' OR paid_at IS NOT NULL",
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_constraint(
        'ck_repayment_schedules_paid_at_required',
        'repayment_schedules',
        type_='check',
    )

    op.drop_constraint(
        'ck_repayment_schedules_status',
        'repayment_schedules',
        type_='check',
    )

    op.drop_constraint(
        'ck_repayment_schedules_total_due_consistency',
        'repayment_schedules',
        type_='check',
    )

    op.drop_constraint(
        'ck_repayment_schedules_outstanding_principal_non_negative',
        'repayment_schedules',
        type_='check',
    )

    op.drop_constraint(
        'ck_repayment_schedules_total_due_non_negative',
        'repayment_schedules',
        type_='check',
    )

    op.drop_constraint(
        'ck_repayment_schedules_interest_due_non_negative',
        'repayment_schedules',
        type_='check',
    )

    op.drop_constraint(
        'ck_repayment_schedules_principal_due_non_negative',
        'repayment_schedules',
        type_='check',
    )

    op.drop_constraint(
        'ck_repayment_schedules_installment_number_positive',
        'repayment_schedules',
        type_='check',
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        'uq_repayment_schedules_disbursement_installment',
        'repayment_schedules',
        type_='unique'
    )

    op.drop_index(
        'ix_repayment_schedules_disbursement_installment',
        table_name='repayment_schedules'
    )

    op.drop_index(
        'ix_repayment_schedules_application_installment',
        table_name='repayment_schedules'
    )
    # ### end Alembic commands ###