"""harden repayment integrity

Revision ID: 5bdfbcbe3e44
Revises: 527b7e142136
Create Date: 2026-10-05 05:37:51.432215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5bdfbcbe3e44'
down_revision: Union[str, Sequence[str], None] = '527b7e142136'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        'ix_repayments_application_created',
        'repayments',
        ['application_id', 'created_at'],
        unique=False
    )

    op.create_index(
        'ix_repayments_schedule_created',
        'repayments',
        ['repayment_schedule_id', 'created_at'],
        unique=False
    )
    # ### end Alembic commands ###
    op.create_check_constraint(
        "ck_repayments_amount_positive",
        "repayments",
        "repayment_amount > 0",
    )

    op.create_check_constraint(
        "ck_repayments_principal_allocated_non_negative",
        "repayments",
        "principal_allocated IS NULL OR principal_allocated >= 0",
    )

    op.create_check_constraint(
        "ck_repayments_interest_allocated_non_negative",
        "repayments",
        "interest_allocated IS NULL OR interest_allocated >= 0",
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_constraint(
        "ck_repayments_interest_allocated_non_negative",
        "repayments",
        type_="check",
    )

    op.drop_constraint(
        "ck_repayments_principal_allocated_non_negative",
        "repayments",
        type_="check",
    )

    op.drop_constraint(
        "ck_repayments_amount_positive",
        "repayments",
        type_="check",
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        'ix_repayments_schedule_created',
        table_name='repayments'
    )

    op.drop_index(
        'ix_repayments_application_created',
        table_name='repayments'
    )
    # ### end Alembic commands ###
