"""add decision traces

Revision ID: 7763d8a9ff91
Revises: 9546176c87dd
Create Date: 2026-10-05 10:17:46.510566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7763d8a9ff91'
down_revision: Union[str, Sequence[str], None] = '9546176c87dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_underwriting_feature_snapshots_application_created'), table_name='underwriting_feature_snapshots')
    op.drop_table('underwriting_feature_snapshots')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('underwriting_feature_snapshots',
    sa.Column('feature_snapshot_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('application_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('decision_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('model_version', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('feature_version', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('features', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['loan_applications.application_id'], name=op.f('underwriting_feature_snapshots_application_id_fkey')),
    sa.ForeignKeyConstraint(['decision_id'], ['credit_decisions.decision_id'], name=op.f('underwriting_feature_snapshots_decision_id_fkey')),
    sa.PrimaryKeyConstraint('feature_snapshot_id', name=op.f('underwriting_feature_snapshots_pkey')),
    sa.UniqueConstraint('decision_id', name=op.f('uq_underwriting_feature_snapshots_decision_id'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_underwriting_feature_snapshots_application_created'), 'underwriting_feature_snapshots', ['application_id', 'created_at'], unique=False)
    # ### end Alembic commands ###
