"""harden bureau report integrity

Revision ID: 7ccac992840d
Revises: 9d41fb34e6cd
Create Date: 2026-10-05 01:57:01.941699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ccac992840d'
down_revision: Union[str, Sequence[str], None] = '9d41fb34e6cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_bureau_reports_application_fetched', 'bureau_reports', ['application_id', 'fetched_at'], unique=False)
    # ### end Alembic commands ###
    op.create_check_constraint(
        "ck_bureau_reports_dpd_non_negative",
        "bureau_reports",
        "dpd IS NULL OR dpd >= 0",
    )

    op.create_check_constraint(
        "ck_bureau_reports_active_loans_non_negative",
        "bureau_reports",
        "active_loans IS NULL OR active_loans >= 0",
    )

    op.create_check_constraint(
        "ck_bureau_reports_total_outstanding_non_negative",
        "bureau_reports",
        "total_outstanding IS NULL OR total_outstanding >= 0",
    )

    op.create_check_constraint(
        "ck_bureau_reports_write_offs_non_negative",
        "bureau_reports",
        "write_offs IS NULL OR write_offs >= 0",
    )

    op.create_check_constraint(
        "ck_bureau_reports_enquiries_non_negative",
        "bureau_reports",
        "enquiries IS NULL OR enquiries >= 0",
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_constraint(
        "ck_bureau_reports_dpd_non_negative",
        "bureau_reports",
        type_="check",
    )

    op.drop_constraint(
        "ck_bureau_reports_active_loans_non_negative",
        "bureau_reports",
        type_="check",
    )

    op.drop_constraint(
        "ck_bureau_reports_total_outstanding_non_negative",
        "bureau_reports",
        type_="check",
    )

    op.drop_constraint(
        "ck_bureau_reports_write_offs_non_negative",
        "bureau_reports",
        type_="check",
    )

    op.drop_constraint(
        "ck_bureau_reports_enquiries_non_negative",
        "bureau_reports",
        type_="check",
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_bureau_reports_application_fetched', table_name='bureau_reports')
    # ### end Alembic commands ###