"""harden device behaviour integrity

Revision ID: 850d481c77a2
Revises: cd3f951da78f
Create Date: 2026-10-05 02:20:28.064609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '850d481c77a2'
down_revision: Union[str, Sequence[str], None] = 'cd3f951da78f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_device_behaviour_application_analyzed', 'device_behaviour', ['application_id', 'analyzed_at'], unique=False)
    # ### end Alembic commands ###
    op.create_check_constraint(
        "ck_device_behaviour_device_age_days_non_negative",
        "device_behaviour",
        "device_age_days IS NULL OR device_age_days >= 0",
    )

    op.create_check_constraint(
        "ck_device_behaviour_login_count_non_negative",
        "device_behaviour",
        "login_count IS NULL OR login_count >= 0",
    )

    op.create_check_constraint(
        "ck_device_behaviour_session_count_non_negative",
        "device_behaviour",
        "session_count IS NULL OR session_count >= 0",
    )

    op.create_check_constraint(
        "ck_device_behaviour_failed_login_count_non_negative",
        "device_behaviour",
        "failed_login_count IS NULL OR failed_login_count >= 0",
    )

    op.create_check_constraint(
        "ck_device_behaviour_application_velocity_non_negative",
        "device_behaviour",
        "application_velocity IS NULL OR application_velocity >= 0",
    )

    op.create_check_constraint(
        "ck_device_behaviour_device_velocity_non_negative",
        "device_behaviour",
        "device_velocity IS NULL OR device_velocity >= 0",
    )

    op.create_check_constraint(
        "ck_device_behaviour_ip_velocity_non_negative",
        "device_behaviour",
        "ip_velocity IS NULL OR ip_velocity >= 0",
    )

    op.create_check_constraint(
        "ck_device_behaviour_risk_score_range",
        "device_behaviour",
        "behavioural_risk_score IS NULL OR "
        "(behavioural_risk_score >= 0 AND behavioural_risk_score <= 100)",
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_constraint(
        "ck_device_behaviour_device_age_days_non_negative",
        "device_behaviour",
        type_="check",
    )

    op.drop_constraint(
        "ck_device_behaviour_login_count_non_negative",
        "device_behaviour",
        type_="check",
    )

    op.drop_constraint(
        "ck_device_behaviour_session_count_non_negative",
        "device_behaviour",
        type_="check",
    )

    op.drop_constraint(
        "ck_device_behaviour_failed_login_count_non_negative",
        "device_behaviour",
        type_="check",
    )

    op.drop_constraint(
        "ck_device_behaviour_application_velocity_non_negative",
        "device_behaviour",
        type_="check",
    )

    op.drop_constraint(
        "ck_device_behaviour_device_velocity_non_negative",
        "device_behaviour",
        type_="check",
    )

    op.drop_constraint(
        "ck_device_behaviour_ip_velocity_non_negative",
        "device_behaviour",
        type_="check",
    )

    op.drop_constraint(
        "ck_device_behaviour_risk_score_range",
        "device_behaviour",
        type_="check",
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_device_behaviour_application_analyzed', table_name='device_behaviour')
    # ### end Alembic commands ###
