"""harden loan application integrity

Revision ID: 861afe76055e
Revises: 317147dd64fa
Create Date: 2026-10-05 01:29:51.669061

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '861afe76055e'
down_revision: Union[str, Sequence[str], None] = '317147dd64fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_loan_applications_customer_created', 'loan_applications', ['customer_id', 'created_at'], unique=False)
    # ### end Alembic commands ###
    
    op.create_check_constraint(
        "ck_loan_applications_requested_amount_non_negative",
        "loan_applications",
        "requested_amount >= 0",
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_constraint(
        "ck_loan_applications_requested_amount_non_negative",
        "loan_applications",
        type_="check",
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_loan_applications_customer_created', table_name='loan_applications')
    # ### end Alembic commands ###