"""harden customer integrity

Revision ID: 9959ccf202c8
Revises: 861afe76055e
Create Date: 2026-10-05 01:40:41.502942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9959ccf202c8'
down_revision: Union[str, Sequence[str], None] = '861afe76055e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_customers_pan', 'customers', ['pan'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_customers_pan', table_name='customers')
    # ### end Alembic commands ###