"""harden internal history integrity

Revision ID: 9a3badf77776
Revises: 850d481c77a2
Create Date: 2026-10-05 02:30:21.239030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a3badf77776'
down_revision: Union[str, Sequence[str], None] = '850d481c77a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_internal_history_application_analyzed', 'internal_history', ['application_id', 'analyzed_at'], unique=False)
    # ### end Alembic commands ###
    op.create_check_constraint(
        "ck_internal_history_previous_loans_count_non_negative",
        "internal_history",
        "previous_loans_count IS NULL OR previous_loans_count >= 0",
    )

    op.create_check_constraint(
        "ck_internal_history_active_loans_count_non_negative",
        "internal_history",
        "active_loans_count IS NULL OR active_loans_count >= 0",
    )

    op.create_check_constraint(
        "ck_internal_history_closed_loans_count_non_negative",
        "internal_history",
        "closed_loans_count IS NULL OR closed_loans_count >= 0",
    )

    op.create_check_constraint(
        "ck_internal_history_total_previous_exposure_non_negative",
        "internal_history",
        "total_previous_exposure IS NULL OR total_previous_exposure >= 0",
    )

    op.create_check_constraint(
        "ck_internal_history_total_outstanding_amount_non_negative",
        "internal_history",
        "total_outstanding_amount IS NULL OR total_outstanding_amount >= 0",
    )

    op.create_check_constraint(
        "ck_internal_history_dpd_count_non_negative",
        "internal_history",
        "dpd_count IS NULL OR dpd_count >= 0",
    )

    op.create_check_constraint(
        "ck_internal_history_max_dpd_non_negative",
        "internal_history",
        "max_dpd IS NULL OR max_dpd >= 0",
    )

    op.create_check_constraint(
        "ck_internal_history_overdue_amount_non_negative",
        "internal_history",
        "overdue_amount IS NULL OR overdue_amount >= 0",
    )

    op.create_check_constraint(
        "ck_internal_history_write_off_count_non_negative",
        "internal_history",
        "write_off_count IS NULL OR write_off_count >= 0",
    )

    op.create_check_constraint(
        "ck_internal_history_settlement_count_non_negative",
        "internal_history",
        "settlement_count IS NULL OR settlement_count >= 0",
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_constraint(
        "ck_internal_history_previous_loans_count_non_negative",
        "internal_history",
        type_="check",
    )

    op.drop_constraint(
        "ck_internal_history_active_loans_count_non_negative",
        "internal_history",
        type_="check",
    )

    op.drop_constraint(
        "ck_internal_history_closed_loans_count_non_negative",
        "internal_history",
        type_="check",
    )

    op.drop_constraint(
        "ck_internal_history_total_previous_exposure_non_negative",
        "internal_history",
        type_="check",
    )

    op.drop_constraint(
        "ck_internal_history_total_outstanding_amount_non_negative",
        "internal_history",
        type_="check",
    )

    op.drop_constraint(
        "ck_internal_history_dpd_count_non_negative",
        "internal_history",
        type_="check",
    )

    op.drop_constraint(
        "ck_internal_history_max_dpd_non_negative",
        "internal_history",
        type_="check",
    )

    op.drop_constraint(
        "ck_internal_history_overdue_amount_non_negative",
        "internal_history",
        type_="check",
    )

    op.drop_constraint(
        "ck_internal_history_write_off_count_non_negative",
        "internal_history",
        type_="check",
    )

    op.drop_constraint(
        "ck_internal_history_settlement_count_non_negative",
        "internal_history",
        type_="check",
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_internal_history_application_analyzed', table_name='internal_history')
    # ### end Alembic commands ###