"""harden document integrity

Revision ID: 9d41fb34e6cd
Revises: 9959ccf202c8
Create Date: 2026-10-05 01:51:21.807330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d41fb34e6cd'
down_revision: Union[str, Sequence[str], None] = '9959ccf202c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_documents_application_created', 'documents', ['application_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_documents_application_created', table_name='documents')
    # ### end Alembic commands ###
