"""harden manual review integrity

Revision ID: aa996b5f23c2
Revises: 061e2797c27e
Create Date: 2026-10-05 00:09:51.627848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa996b5f23c2'
down_revision: Union[str, Sequence[str], None] = '061e2797c27e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_manual_reviews_application_status', 'manual_reviews', ['application_id', 'review_status'], unique=False)
    op.create_index('ix_manual_reviews_reviewer_id', 'manual_reviews', ['reviewer_id'], unique=False)
    # ### end Alembic commands ###
    op.create_check_constraint(
        "ck_manual_reviews_status",
        "manual_reviews",
        "review_status IN ('OPEN', 'IN_PROGRESS', 'COMPLETED')",
    )
    op.create_check_constraint(
        "ck_manual_reviews_reviewer_decision",
        "manual_reviews",
        "reviewer_decision IS NULL OR reviewer_decision IN ('APPROVE', 'REJECT')",
    )
    op.create_check_constraint(
        "ck_manual_reviews_completed_decision",
        "manual_reviews",
        "review_status <> 'COMPLETED' OR reviewer_decision IS NOT NULL",
        )
    op.create_check_constraint(
        "ck_manual_reviews_in_progress_reviewer",
        "manual_reviews",
        "review_status <> 'IN_PROGRESS' OR reviewer_id IS NOT NULL",
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_constraint(
        "ck_manual_reviews_in_progress_reviewer",
        "manual_reviews",
        type_="check",
    )

    op.drop_constraint(
        "ck_manual_reviews_completed_decision",
        "manual_reviews",
        type_="check",
    )

    op.drop_constraint(
        "ck_manual_reviews_reviewer_decision",
        "manual_reviews",
        type_="check",
    )

    op.drop_constraint(
        "ck_manual_reviews_status",
        "manual_reviews",
        type_="check",
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_manual_reviews_reviewer_id', table_name='manual_reviews')
    op.drop_index('ix_manual_reviews_application_status', table_name='manual_reviews')
    # ### end Alembic commands ###