"""harden reconciliation integrity

Revision ID: c99cd69e4364
Revises: 506672d91f5c
Create Date: 2026-10-05 08:39:04.111497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c99cd69e4364'
down_revision: Union[str, Sequence[str], None] = '506672d91f5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        'ix_reconciliation_disbursement_created', 
        'reconciliation', 
        ['disbursement_id', 'created_at'], 
        unique=False
    )

    op.create_check_constraint(
        'ck_reconciliation_transaction_amount_non_negative',
        'reconciliation',
        'transaction_amount >= 0',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_constraint(
        'ck_reconciliation_transaction_amount_non_negative',
        'reconciliation',
        type_='check',
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        'ix_reconciliation_disbursement_created',
        table_name='reconciliation')
    # ### end Alembic commands ###
