"""harden employment integrity

Revision ID: cd3f951da78f
Revises: dca10663756d
Create Date: 2026-10-05 02:12:00.081873

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd3f951da78f'
down_revision: Union[str, Sequence[str], None] = 'dca10663756d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_employment_application_analyzed', 'employment', ['application_id', 'analyzed_at'], unique=False)
    # ### end Alembic commands ###
    op.create_check_constraint(
        "ck_employment_monthly_income_non_negative",
        "employment",
        "monthly_income IS NULL OR monthly_income >= 0",
    )

    op.create_check_constraint(
        "ck_employment_vintage_months_non_negative",
        "employment",
        "employment_vintage_months IS NULL OR employment_vintage_months >= 0",
    )

    op.create_check_constraint(
        "ck_employment_business_vintage_months_non_negative",
        "employment",
        "business_vintage_months IS NULL OR business_vintage_months >= 0",
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_constraint(
        "ck_employment_monthly_income_non_negative",
        "employment",
        type_="check",
    )

    op.drop_constraint(
        "ck_employment_vintage_months_non_negative",
        "employment",
        type_="check",
    )

    op.drop_constraint(
        "ck_employment_business_vintage_months_non_negative",
        "employment",
        type_="check",
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_employment_application_analyzed', table_name='employment')
    # ### end Alembic commands ###
