"""harden application document integrity

Revision ID: d7df51ef3783
Revises: 1aaee24ede4e
Create Date: 2026-10-05 07:57:56.828803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7df51ef3783'
down_revision: Union[str, Sequence[str], None] = '1aaee24ede4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_application_documents_application_created', 'application_documents', ['application_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_application_documents_application_created', table_name='application_documents')
    # ### end Alembic commands ###
