"""harden bank analysis integrity

Revision ID: dca10663756d
Revises: 7ccac992840d
Create Date: 2026-10-05 02:05:20.418748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dca10663756d'
down_revision: Union[str, Sequence[str], None] = '7ccac992840d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_bank_analysis_application_analyzed', 'bank_analysis', ['application_id', 'analyzed_at'], unique=False)
    # ### end Alembic commands ###
    op.create_check_constraint(
        "ck_bank_analysis_monthly_credits_non_negative",
        "bank_analysis",
        "monthly_credits IS NULL OR monthly_credits >= 0",
    )

    op.create_check_constraint(
        "ck_bank_analysis_monthly_debits_non_negative",
        "bank_analysis",
        "monthly_debits IS NULL OR monthly_debits >= 0",
    )

    op.create_check_constraint(
        "ck_bank_analysis_existing_emi_non_negative",
        "bank_analysis",
        "existing_emi IS NULL OR existing_emi >= 0",
    )

    op.create_check_constraint(
        "ck_bank_analysis_bounce_count_non_negative",
        "bank_analysis",
        "bounce_count IS NULL OR bounce_count >= 0",
    )

    op.create_check_constraint(
        "ck_bank_analysis_transactions_count_non_negative",
        "bank_analysis",
        "transactions_count IS NULL OR transactions_count >= 0",
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_constraint(
        "ck_bank_analysis_monthly_credits_non_negative",
        "bank_analysis",
        type_="check",
    )

    op.drop_constraint(
        "ck_bank_analysis_monthly_debits_non_negative",
        "bank_analysis",
        type_="check",
    )

    op.drop_constraint(
        "ck_bank_analysis_existing_emi_non_negative",
        "bank_analysis",
        type_="check",
    )

    op.drop_constraint(
        "ck_bank_analysis_bounce_count_non_negative",
        "bank_analysis",
        type_="check",
    )

    op.drop_constraint(
        "ck_bank_analysis_transactions_count_non_negative",
        "bank_analysis",
        type_="check",
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_bank_analysis_application_analyzed', table_name='bank_analysis')
    # ### end Alembic commands ###
