"""harden disbursement integrity

Revision ID: dd8e95c8b927
Revises: 5bdfbcbe3e44
Create Date: 2026-10-05 05:58:32.065770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd8e95c8b927'
down_revision: Union[str, Sequence[str], None] = '5bdfbcbe3e44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        'ix_disbursements_application_created',
        'disbursements',
        ['application_id', 'created_at'], 
        unique=False
    )

    op.create_index(
        'ix_disbursements_status_created',
        'disbursements',
        ['status', 'created_at'],
        unique=False
    )

    op.create_check_constraint(
        "ck_disbursements_amount_positive",
        "disbursements",
        "disbursement_amount > 0",
    )

    op.create_check_constraint(
        "ck_disbursements_retry_attempts_non_negative",
        "disbursements",
        "retry_attempts >= 0",
    )

    op.create_check_constraint(
        "ck_disbursements_status",
        "disbursements",
        "status IN ('CREATED', 'INITIATED', 'PROCESSING', 'PROCESSED', 'FAILED')",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_constraint(
        "ck_disbursements_status",
        "disbursements",
        type_="check",
    )

    op.drop_constraint(
        "ck_disbursements_retry_attempts_non_negative",
        "disbursements",
        type_="check",
    )

    op.drop_constraint(
        "ck_disbursements_amount_positive",
        "disbursements",
        type_="check",
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        'ix_disbursements_status_created', 
        table_name='disbursements'
    )
    
    op.drop_index(
        'ix_disbursements_application_created', 
        table_name='disbursements'
    )
    # ### end Alembic commands ###
